# Header
menu:
  首页: /
  文章: /archives
  关于: /about
# rss: /atom.xml

# Content
excerpt_link: 阅读全文
fancybox: false
mathjax: false

# Sidebar
sidebar: right
widgets:
- recommend_posts
- tagcloud
- category
- archive
- links
- recent_comments

# - recent_posts
# - tag


# Links
links:
  石佳劼的微博: http://weibo.com/605494869/
  石佳劼的知乎: http://www.zhihu.com/people/stone0090/
  石佳劼的简书: http://www.jianshu.com/users/0005893eaff9/latest_articles/
  石佳劼的CSDN: http://blog.csdn.net/shi0090/
  石佳劼的博客园: http://www.cnblogs.com/shi0090/
  石佳劼的GitHub: https://github.com/stone0090/
  
# recommend_posts
recommend_posts:
  DSOframer的简单介绍和资源整理: /2015/09/02/dsoframer-introduction-resources/
  DSOframer微软官方API的查阅方法: /2015/09/11/dsoframer-frequently-asked-question2/
  DSOframer无法正常加载的解决方案: /2015/08/31/dsoframer-frequently-asked-question1/
  C#技术分享-PDF转图片的10种方法: /2012/02/15/office-pdf2image/
  C#技术分享-DOC转图片的3种方法: /2012/02/22/office-doc2image/
  Hexo 官方主题 landscape-plus 优化: /2015/08/29/hexo-theme-landscape-plus-optimize/
  DoNet开源项目-基于jQuery EasyUI的后台管理系统: /2015/08/30/donet-opensource-stonefw-introduction/
  DoNet开源项目-基于Amaze UI的点餐系统: /2016/01/17/donet-opensource-dian-introduction/

# Miscellaneous
google_analytics:
favicon: /img/logo.png
twitter:
google_plus:
fb_admins: 
fb_app_id:

# Duoshuo
duoshuo_shortname: shijiajie

# Baidu share
baidushare: true

# Baidu statistic
baidu_tongji: true