# Header
menu:
  首页: /
  文章: /archives
  关于: /about
# rss: /atom.xml

# Content
excerpt_link: 阅读全文
fancybox: false
mathjax: false

# Sidebar
sidebar: right
widgets:
- tagcloud
- category
- recommend_posts
- links
- archive
# - recent_posts
# - tag

# Links
links:
  石佳劼的微博: http://weibo.com/605494869/
  石佳劼的知乎: http://www.zhihu.com/people/stone0090/
  石佳劼的简书: http://www.jianshu.com/users/0005893eaff9/latest_articles/
  石佳劼的CSDN: http://blog.csdn.net/shi0090/
  石佳劼的博客园: http://www.cnblogs.com/shi0090/
  石佳劼的GitHub: https://github.com/stone0090/
  
# recommend_posts
recommend_posts:
  DSOframer 的简单介绍和资源整理: http://shijiajie.com/2013/01/28/dsoframer-introduction-resources/
  C#技术分享-PDF转图片的10种方法: http://shijiajie.com/2012/02/15/office-pdf2image/
  C#技术分享-DOC转图片的3种方法: http://shijiajie.com/2012/02/22/office-doc2image/

# Miscellaneous
google_analytics:
favicon: /img/logo.png
twitter:
google_plus:
fb_admins: 
fb_app_id:

# Duoshuo
duoshuo_shortname: shijiajie

# Baidu share
baidushare: true

# Baidu statistic
baidu_tongji: true